[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
markers =
    integration: marks tests as integration tests that interact with external services
addopts = --cov=scripts --cov-report=term-missing