FROM golang:1.21.6 as builder

RUN apt-get update && apt-get install -y \
    wget \
    build-essential \
    git \
    cmake

WORKDIR /build
RUN git clone --depth=1 --branch v0.5.7 https://github.com/ollama/ollama.git && \
    cd ollama && \
    CGO_ENABLED=1 GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/ollama .

FROM debian:stable-slim
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/bin/ollama /usr/local/bin/ollama

EXPOSE 11434
ENV OLLAMA_HOST=0.0.0.0

ENTRYPOINT ["/usr/local/bin/ollama"]
CMD ["serve"]