services:
  dp_js:
    build:
      context: .
      dockerfile: ./Dockerfile.v1
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${UID}
        - USER_GID=${GID}
        - VERSSION=${VERSION}
        - REGISTRY=${REGISTRY}
    image: qi/data-platform-dev-container:${VERSION}
    container_name: data-platform-dev-container
    hostname: data-platform-dev.local
    working_dir: /home/${USERNAME}/dev
    ports:
      - 3001:3001
    volumes:
      - ../:/workspace:cached
      - ../js:/home/${USERNAME}/js:cached
      - ../docs/js:/home/${USERNAME}/docs/js:cached
      - ../docs/sketch:/home${USERNAME}/docs/sketch:cached
      # Allow AWS CLI and other tools to read an AWS profile
      #- ~/.aws:/home/node/.aws
    links:
      - "plantuml:plantuml"
    command: sleep infinity

  plantuml: 
    image: plantuml/plantuml-server:v1.2024.7
    ports:
      - "7070:7070"