services:
  dp_js:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${UID}
        - USER_GID=${GID}
        - VERSION=${VERSION}
        - REGISTRY=${REGISTRY}
    image: qi/data-platform-dev-container:${VERSION}
    container_name: data-platform-dev-container
    hostname: data-platform-dev.local
    working_dir: /home/${USERNAME}
    ports:
      - "7071:7071"
    volumes:
      - ../:/workspace:cached
      - ../qi:/home/${USERNAME}/qi:cached
      - ../docs:/home/${USERNAME}/docs:cached
      - ./shared:/shared:cached  # Host-relative path to ensure the same 'shared' access
    networks:
      - qi_db_network
      - redis_network
      - redpanda_network
    command: sleep infinity

networks:
  qi_db_network:
    name: qi_db
  redis_network:
    name: redis_network
  redpanda_network:
    name: redpanda_network