x-common-networks: &common-networks
  networks:
    - qi_db_network
    - redis_network
    - redpanda_network

name: qi-v2-dp

services:
  coder:
    build:
      context: .
      dockerfile: ./python/Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${UID}
        USER_GID: ${GID}
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        PYTHON_WORKDIR: ${PYTHON_WORKDIR}
    image: ${REGISTRY}/qi/coder:${VERSION}
    container_name: qi-v2-dp-coder
    hostname: coder
    working_dir: ${PYTHON_WORKDIR}
    volumes:
      - ../services/ai/python:/home/${USERNAME}/python:cached
    environment:
      TOKENIZERS_PARALLELISM: "true"
      OMP_NUM_THREADS: "8"
      MKL_NUM_THREADS: "8"
      PYTHON_WORKDIR: ${PYTHON_WORKDIR}
      USERNAME: ${USERNAME}
      USER_UID: ${UID}
      USER_GID: ${GID}
      HF_HOME: /home/${USER}/python/.cache/huggingface
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: "60129542144"
        reservations:
          memory: "34359738368"
    <<: *common-networks

  dp_js:
    build:
      context: .
      dockerfile: ./qi/Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${UID}
        USER_GID: ${GID}
        REGISTRY: ${REGISTRY}
        VERSION: ${VERSION}
        QI_WORKDIR: ${QI_WORKDIR}
    image: ${REGISTRY}/qi/data-platform-dev-container:${VERSION}
    working_dir: ${QI_WORKDIR}
    environment:
      - QI_WORKDIR=${QI_WORKDIR}
      - USERNAME=${USERNAME}
      - USER_UID=${UID}
      - USER_GID=${GID}
    volumes:
      - ../qi:/home/${USERNAME}/qi:cached
    <<: *common-networks

networks:
  qi_db_network:
    external: true
    name: qi_db
  redis_network:
    external: true
    name: redis_network
  redpanda_network:
    external: true
    name: redpanda_network
